[project]
name = "wsq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ellecarey", email = "elle.carey@yahoo.co.uk" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
]

[dependency-groups]
dev = [
    "nbstripout>=0.9.1",
]
